# Generated by Django 4.0.4 on 2022-06-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_acomodacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='andar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='capacidade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Livre', 'Livre'), ('Desativado', 'Desativado'), ('Em manutenção', 'Em manutenção')], max_length=15),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tiposacomodacao'),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='unidade',
            field=models.IntegerField(unique=True),
        ),
    ]
