# Generated by Django 4.0.4 on 2022-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_acomodacao_andar_alter_acomodacao_capacidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Desativado', 'Desativado'), ('Em manutenção', 'Em manutenção'), ('Livre', 'Livre')], max_length=15),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
