# Generated by Django 4.0.4 on 2022-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_acomodacao_status_alter_acomodacao_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Ocupado', 'Ocupado'), ('Em manutenção', 'Em manutenção'), ('Desativado', 'Desativado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='valor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
