# Generated by Django 4.0.4 on 2022-06-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_acomodacao_status_alter_acomodacao_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Em manutenção', 'Em manutenção'), ('Ocupado', 'Ocupado'), ('Desativado', 'Desativado'), ('Reservado', 'Reservado'), ('Livre', 'Livre')], max_length=15),
        ),
    ]
