# Generated by Django 4.0.4 on 2022-06-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='ramal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Desativado', 'Desativado'), ('Reservado', 'Reservado'), ('Livre', 'Livre'), ('Em manutenção', 'Em manutenção'), ('Ocupado', 'Ocupado')], max_length=15),
        ),
        migrations.CreateModel(
            name='Diarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospedes', models.IntegerField(blank=True, null=True)),
                ('entrada', models.DateField(blank=True, null=True)),
                ('saida', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField()),
                ('adiantamento', models.FloatField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.acomodacao')),
            ],
        ),
    ]
