# Generated by Django 4.0.4 on 2022-06-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_acomodacao_ramal_alter_acomodacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Desativado', 'Desativado'), ('Em manutenção', 'Em manutenção'), ('Ocupado', 'Ocupado'), ('Livre', 'Livre'), ('Reservado', 'Reservado')], max_length=15),
        ),
    ]
