# Generated by Django 4.0.4 on 2022-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Em manutenção', 'Em manutenção'), ('Reservado', 'Reservado'), ('Livre', 'Livre'), ('Desativado', 'Desativado')], max_length=15),
        ),
    ]
