# Generated by Django 4.0.4 on 2022-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomodacao',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Em manutenção', 'Em manutenção'), ('Reservado', 'Reservado'), ('Livre', 'Livre')], max_length=15),
        ),
    ]
