# Generated by Django 4.0.4 on 2022-06-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_acomodacao_situacao_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Reservado', 'Reservado'), ('Em manutenção', 'Em manutenção'), ('Livre', 'Livre')], max_length=15),
        ),
    ]
