# Generated by Django 4.0.4 on 2022-06-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='situacao',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Em manutenção', 'Em manutenção'), ('Livre', 'Livre'), ('Reservado', 'Reservado')], max_length=15),
        ),
    ]
