# Generated by Django 4.0.4 on 2022-06-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_acomodacao_situacao_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Reservado', 'Reservado'), ('Ocupado', 'Ocupado'), ('Em manutenção', 'Em manutenção')], max_length=15),
        ),
    ]
