# Generated by Django 4.0.4 on 2022-06-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_acomodacao_situacao_alter_acomodacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='situacao',
            field=models.CharField(choices=[('True', 'Ativo'), ('False', 'Inativo')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Ocupado', 'Ocupado'), ('Livre', 'Livre'), ('Em manutenção', 'Em manutenção')], max_length=15),
        ),
    ]
