# Generated by Django 4.0.4 on 2022-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_acomodacao_situacao_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='situacao',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Reservado', 'Reservado'), ('Em manutenção', 'Em manutenção'), ('Ocupado', 'Ocupado')], max_length=15),
        ),
    ]
