# Generated by Django 4.0.4 on 2022-06-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Em manutenção', 'Em manutenção'), ('Livre', 'Livre'), ('Ocupado', 'Ocupado'), ('Reservado', 'Reservado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='diarias',
            name='valor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
