# Generated by Django 4.0.4 on 2022-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_acomodacao_status_alter_diarias_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Em manutenção', 'Em manutenção'), ('Livre', 'Livre'), ('Ocupado', 'Ocupado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='diarias',
            name='adiantamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
