# Generated by Django 4.0.4 on 2022-06-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_acomodacao_status_alter_diarias_adiantamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Em manutenção', 'Em manutenção'), ('Reservado', 'Reservado'), ('Ocupado', 'Ocupado'), ('Livre', 'Livre')], max_length=15),
        ),
    ]
