# Generated by Django 4.0.4 on 2022-06-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_acomodacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Em manutenção', 'Em manutenção'), ('Reservado', 'Reservado'), ('Ocupado', 'Ocupado')], max_length=15),
        ),
    ]
