# Generated by Django 4.0.4 on 2022-06-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_acomodacao_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarias',
            old_name='valor',
            new_name='total_diaria',
        ),
        migrations.AddField(
            model_name='diarias',
            name='qnt_diarias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diarias',
            name='valor_diaria',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='situacao',
            field=models.CharField(choices=[('Inativo', 'Inativo'), ('Ativo', 'Ativo')], default=True, max_length=10),
        ),
    ]
