# Generated by Django 4.0.4 on 2022-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_valor_diarias_total_diaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='situacao',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Em manutenção', 'Em manutenção'), ('Livre', 'Livre'), ('Ocupado', 'Ocupado')], max_length=15),
        ),
    ]
